apiVersion: v1
kind: Service
metadata:
  namespace: devops
  name: front-app-svc
  labels:
    app: front-app
spec:
  type: NodePort
  selector:
    app: front-app
  ports:
    - name: port
      port: 3000
      targetPort: 80