sonar.projectKey=devops_frontend
sonar.projectName=Devops frontend

sonar.sources=src
sonar.exclusions=src/index.tsx,src/App.tsx, src/reportWebVitals.ts,src/react-app-env.d.ts
sonar.tests=src
sonar.test.inclusions=src/__tests__/*.test.tsx, src/utils/__jest__/*.test.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.newCode.referenceBranch=main
sonar.qualitygate.wait=true