apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: devops
  labels:
    app: backend-app
spec:
  selector:
    app:  backend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
