apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 1karinav/avia-back:latest
        ports:
        - name: http
          protocol: TCP
          containerPort: 8080
        env:
        - name: DEBUG
          value: "true"
        - name: SPRINGDOC_PATH
          value: "/api-docs"
        - name: SPRINGDOC_UI_PATH
          value: "/swagger-ui/index.html"
        - name: DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: DATASOURCE_URL
          value: "jdbc:postgresql://localhost:5432/aviatracking"
        - name: APP_NAME
          value: "devops-back"
        - name: DATASOURCE_USERNAME
          value: "postgres"
        - name: DATASOURCE_PASSWORD
          value: "postgres"
        resources:
          requests:
            cpu: "500m"
            memory: 500Mi
          limits:
            cpu: "500m"
            memory: 1000Mi
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: aviatracking
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "1"
            memory: 2Gi
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: volume-backend-pvc-2